/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectalgorithm;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author 215028172
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    static ArrayList<Course> ar;
    String array[] = new String[20];
    int x;

    public NewJFrame(ArrayList<Course> ar) {
        initComponents();
        this.ar = ar;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jButton1.setText("Show");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("Course Name");

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jTextField1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
      void meathod(ArrayList<Course> al, String str1, Integer f) {
        boolean flag = true;

        int f2 = 0;
        outerloop:
        while (flag) {
            int var = 1;
            for (Course c : al) {
                if (c.getName().equals(str1)) {
                    if (c.getPrerequisite().length > 1) {
                        for (int w = 0; w < c.getPrerequisite().length; w++) {
                            //jTextArea1.setText(jTextArea1.getText() + "\n" + c.getPrerequisite()[w]);
                            if (!Arrays.asList(array).contains(c.getPrerequisite()[w])) {
                                array[x] = c.getPrerequisite()[w];
                                x++;
                            }
                            str1 = c.getPrerequisite()[w];
                            f2 = 1;
                            f = 1;
                            meathod(al, str1, f);

                        }

                        break outerloop;
                    } else if (c.getPrerequisite()[0].equals(" ") && f == 0) {
                        JOptionPane.showMessageDialog(this, "Course has no prerequisite");
                        break outerloop;
                    } else {
                        if (c.getPrerequisite()[0].equals(" ")) {
                            break outerloop;
                        }
                        //jTextArea1.setText(jTextArea1.getText() + "\n" + c.getPrerequisite()[0]);
                        if (!Arrays.asList(array).contains(c.getPrerequisite()[0])) {
                            array[x] = c.getPrerequisite()[0];
                            x++;
                        }
                        str1 = c.getPrerequisite()[0];
                        f = 1;
                        break;
                    }

                }
                if (var == al.size() && f2 == 0) {
                    JOptionPane.showMessageDialog(this, "enter valid course name.");
                    flag = false;
                }
                var++;
            }
        }
    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Arrays.fill(array, null);
        x = 0;
        jTextArea1.setText("");
        String ar1[] = new String[50];
        Scanner s = null;
        ArrayList<Course> al = ar;

        String str1 = jTextField1.getText();
        boolean flag = true;
        int f = 0;
        int aa = 0;
        outerloop:
        while (flag) {
            int var = 1;
            for (Course c : al) {
                if (c.getName().equals(str1)) {
                    if (c.getPrerequisite().length > 1) {
                        for (int w = 0; w < c.getPrerequisite().length; w++) {
                            //jTextArea1.setText(jTextArea1.getText() + "\n" + c.getPrerequisite()[w]);
                            if (!Arrays.asList(array).contains(c.getPrerequisite()[w])) {
                                array[x] = c.getPrerequisite()[w];
                                x++;
                            }
                            str1 = c.getPrerequisite()[w];
                            f = 1;
                            meathod(al, str1, f);

                        }

                        break outerloop;
                    } else if (c.getPrerequisite()[0].equals(" ") && f == 0) {
                        JOptionPane.showMessageDialog(this, "Course has no prerequisite");
                        break outerloop;
                    } else {
                        if (c.getPrerequisite()[0].equals(" ")) {
                            break outerloop;
                        }
                        //jTextArea1.setText(jTextArea1.getText() + "\n" + c.getPrerequisite()[0]);
                        if (!Arrays.asList(array).contains(c.getPrerequisite()[0])) {
                            array[x] = c.getPrerequisite()[0];
                            x++;
                        }
                        str1 = c.getPrerequisite()[0];
                        f = 1;
                        break;
                    }

                }
                if (var == al.size()) {
                    JOptionPane.showMessageDialog(this, "enter valid course name.");
                    flag = false;
                }
                var++;
            }
        }
        int flag1 = 0;
        for (String dd : array) {
            if (dd != null) {
                if (flag1 == 0) {
                    jTextArea1.setText(dd);
                    flag1=1;
                } else {
                    jTextArea1.setText(jTextArea1.getText() + "\n" + dd);
                }

            }

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MainMenu m=new MainMenu(ar);
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame(ar).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
